### PR TITLE
Add an ability to bind associations with bindableTo property in domains

### PR DESCRIPTION
**Pull request by NickPavlov**
Add an ability to bind associations with bindableTo property in domains

### CODE REVIEW

**Comment by basejump** [comment]
interesting concept. Lets work through this as I think it might be on the wrong side. in the rally use case, the Location doesn't really need to know about what it belongs to right? The org just needs to know that it will have one that belongs to it right?

**Comment by NickPavlov** [comment]
In our case both Org and Location have fields which point to each other. I mean Location has org field and Org has location field. So this type of relationship looks very similar to belongsTo, but of course without cascading stuff.

The reason why I decided to place 'bindableTo' to an associated domain (like Location) just to be consistent with Grails approach for 'belongsTo'. Since we need something similar to belongsTo, but without adding any relations.

But yes, I think you idea is more reasonable.So, I need to think on the new name for that, because in this case it's not 'bindableTo'

**Comment by snimavat** [comment]
Personall in my opinion, for databinding, the declaration of which association is bindable should be in Org and not in Location

When binding, Org says, these of my associations are bindable, even if they dont belong to me

**Comment by NickPavlov** [comment]
@basejump I've updated the code to use bindable in a parent domain.
I decided to not create the new pull-request just to keep history here

**Comment by NickPavlov** [comment]
@basejump now map binder uses bindable property from constraints. So now its two cases when an association would be binded: 1) it has relations like belongsTo, 2) we explicitly specify constraint 'bindable: true'.
In case this property is null and there is no stuff like belongsTo, map binder will not bind the association (like it actually works right now, so i didn't change the default behavior, just added the option to specify bindable if its needed)

**Comment by basejump** [comment]
this is going to fail the performance benchmarks with the call to look up the constraints on every field call.

**Comment by basejump** [comment]
@NickPavlov the getBindingIncludeList is already called to get the cache. don't re-look up

**Comment by basejump** [comment]
I mocked out how the bindAssoc method should look like. See the notes and FIXME for things that need to be looked at, needs some more tests to deal with the scenarios

**Comment by NickPavlov** [comment]
@basejump I have an idea about handling property names with explicit binding keyword - maybe it would be profitable to store properties which have explicit bindable:true in a separate map instead of adding the keyword to the property and put it to white list? it this case there is no need to use the keyword and exclude these properties from white list in fastBind()

**Pull request merged**
